site_name: PlasmidProfiler
site_url: http://plasmidprofiler.readthedocs.org
site_description:  Plasmid Profiler Pipeline, Heatmap display of plasmid content in WGS data.
repo_url: https://github.com/phac-nml/plasmidprofiler-galaxy/
pages:
- Home: 'index.md'
- Galaxy:
    - 'Usage': 'galaxy/usage.md'
    - 'Input': 'galaxy/input.md'
    - 'Output': 'galaxy/output.md'
- Installation:
    - 'Home': 'install/index.md'
    - 'Docker': 'install/docker.md'
    - 'R - CRAN': 'install/r-cran.md'
    - 'Galaxy': 'install/galaxy.md'
    - 'Versions': 'install/versions.md'
- Examples:
    - 'Example Run': 'examples/example-run.md'
- Developer:
    - 'Upgrading' : 'developer/upgrading.md'
theme: readthedocs
